"""empty message

Revision ID: 0848d2ffb287
Revises: 43998419409a
Create Date: 2020-03-04 23:24:24.252474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0848d2ffb287'
down_revision = '43998419409a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('coin_pouch', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('starting_room', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'nodes', ['starting_room'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'starting_room')
    op.drop_column('users', 'coin_pouch')
    # ### end Alembic commands ###
