"""empty message

Revision ID: 1d89b0866af8
Revises: 0fbd0dd325f9
Create Date: 2020-03-06 15:34:26.380883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d89b0866af8'
down_revision = '0fbd0dd325f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'inventory', ['id'])
    op.create_unique_constraint(None, 'items', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', type_='unique')
    op.drop_constraint(None, 'inventory', type_='unique')
    # ### end Alembic commands ###
