"""empty message

Revision ID: 2a149b4f95f9
Revises: 9fd182561c07
Create Date: 2020-03-08 17:36:13.047451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a149b4f95f9'
down_revision = '9fd182561c07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'inventory', ['id'])
    op.create_unique_constraint(None, 'items', ['id'])
    op.add_column('links', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('links', 'id')
    op.drop_constraint(None, 'items', type_='unique')
    op.drop_constraint(None, 'inventory', type_='unique')
    # ### end Alembic commands ###
