"""empty message

Revision ID: 43998419409a
Revises: 689018b62fdf
Create Date: 2020-03-03 22:57:23.520082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43998419409a'
down_revision = '689018b62fdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
