"""empty message

Revision ID: 74900f38117f
Revises: 1d89b0866af8
Create Date: 2020-03-06 23:55:49.947873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74900f38117f'
down_revision = '1d89b0866af8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_key', sa.String()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'auth_key')
    # ### end Alembic commands ###
